### PR TITLE
save register states, and apply them later

### PR DESCRIPTION
**Pull request by unkadoug**
Pull out of dwarf_reg_state the fields specifically related to caching, and put them in dwarf_reg_cache_entry.  That way, to the extent dwarf_reg_states may become exposed, they'll be smaller, without extraneous fields.

### CODE REVIEW

**Comment by unkadoug** [comment]
The difference between the last test-passing version, and the last test-failing version, is just the addition of new functions.  No functions part of 'make check' are modified.  Any clues about what's wrong, anybody?

**Comment by djwatson** [comment]
If you click on the red X it should show the test output.  One of the unittests checks that only the expected functions are exported, it looks like you added new external interface but didn't update the test.

```
  ERROR: Extraneous symbols:
00000000000035a0 T _ULx86_64_apply_reg_state
00000000000035b0 T _ULx86_64_reg_states_iterate
  ERROR: Extraneous symbols:
0000000000003d60 T _Ux86_64_apply_reg_state
0000000000003d70 T _Ux86_64_reg_states_iterate
```

Can you rebase on master and drop the first four commits also?  

I've started reviewing, but haven't made it through yet

**Comment by unkadoug** [comment]
The I tried to 'rebase', but I don't know whether I actually did anything.
Still a git rookie.

 1116  git rebase master
 1117  git rebase --continue
 1118  git rebase --skip
 1119  git push https://github.com/unkadoug/libunwind reg2
 1120  git pull
 1121  git pull https://github.com/unkadoug/libunwind reg2
 1122  git push https://github.com/unkadoug/libunwind reg2

The error logs show seg faults I can't account for.  Meanwhile, my version
of tests/check-namespace.sh already includes:

    match _UL${plat}_apply_reg_state
    match _UL${plat}_reg_states_iterate
    match _U${plat}_apply_reg_state
    match _U${plat}_reg_states_iterate

else I couldn't pass 'make check' on my machine, which I can.

Doug

**Comment by djwatson** [comment]
> The error logs show seg faults I can't account for.  Meanwhile, my version
> of tests/check-namespace.sh already includes:
> 
>     match _UL${plat}_apply_reg_state
>     match _UL${plat}_reg_states_iterate
>     match _U${plat}_apply_reg_state
>     match _U${plat}_reg_states_iterate
> 
> else I couldn't pass 'make check' on my machine, which I can.
> 

It looks like this change didn't get uploaded to github then, I don't see any files in test directory changed

Try something like:
(assuming libunwind is https://github.com/libunwind/libunwind.git)

> git fetch libunwind
> git rebase -i libunwind/master
  edit the interactive file, drop first four commits
>  git push https://github.com/unkadoug/libunwind reg2

**Comment by unkadoug** [comment]
Nothing is working.

$ git fetch libunwind
fatal: 'libunwind' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
$ git rebase -i libunwind/master
fatal: Needed a single revision
invalid upstream libunwind/master

I'm trying to blow everything up and start over, but I can't get that to
happen either, at the moment.

Doug

**Comment by djwatson** [comment]
git remote add libunwind https://github.com/libunwind/libunwind.git

**Comment by unkadoug** [comment]
Thanks for the help.

Do you know how I can generate *.man files from the *.tex files I’ve written?

Any questions about the patch?

Doug

**Pull request closed without merging**
