### PR TITLE
Fix undefined behavior issues in aarch64

### LINKED ISSUE #412: ubsan discovers out of bounds index on aarch64
aarch64/Ginit.c:53:33: runtime error: index 32 out of bounds for type 'uint64_t [31]

Digging in a lite: looking at the containing structure, unw_sigcontext, there's a declaration like:
uint64_t regs[31];
uint64_t sp;
uint64_t pc;
Which makes a little sense, in that indexing regs[31] will actually pick up the sp, perhaps as is natrually intended, and then a "shortcut" of regs[32] picks up the pc. Maybe...

Perhaps  this intent could be expressed by an appropriate use of a union, and avoid this runtime error.

The ubsan also finds other runtime errors.

See also:

https://github.com/dotnet/runtime/issues/74390

Environment:
Running on ubuntu linux 22.04 on ARM64 platform, doing:
./configure CFLAGS=-fsanitize=undefined CXXFLAGS=-fsanitize=undefined
make
make check

### PR DESCRIPTION
**Pull request by am11**
Fixes #412.

### CODE REVIEW

**Comment by RobertHenry6bev** [comment]
What is the status of getting this PR accepted and committed?

**Comment by djwatson** [comment]
LGTM, thanks.  build failures look unrelated afaict

**Comment by MikaelUrankar** [comment]
This breaks on FreeBSD:
```
In file included from aarch64/Linit.c:4:
aarch64/Ginit.c:55:29: error: no member named 'sp' in 'struct __mcontext'
    return &uc->uc_mcontext.sp;
            ~~~~~~~~~~~~~~~ ^
aarch64/Ginit.c:57:29: error: no member named 'gp_elr' in 'struct __mcontext'
    return &uc->uc_mcontext.gp_elr;
            ~~~~~~~~~~~~~~~ ^
```

**Comment by MikaelUrankar** [comment]
```
diff --git a/src/aarch64/Ginit.c b/src/aarch64/Ginit.c
index 15fc3b9d..34e5c39a 100644
--- a/src/aarch64/Ginit.c
+++ b/src/aarch64/Ginit.c
@@ -52,9 +52,9 @@ uc_addr (unw_tdep_context_t *uc, int reg)
   else if (reg == UNW_AARCH64_X30)
     return &uc->uc_mcontext.mc_gpregs.gp_lr;
   else if (reg == UNW_AARCH64_SP)
-    return &uc->uc_mcontext.sp;
+    return &uc->uc_mcontext.mc_gpregs.gp_sp;
   else if (reg == UNW_AARCH64_PC)
-    return &uc->uc_mcontext.gp_elr;
+    return &uc->uc_mcontext.mc_gpregs.gp_elr;
   else if (reg >= UNW_AARCH64_V0 && reg <= UNW_AARCH64_V31)
     return &GET_FPCTX(uc)->uc_mcontext.mc_fpregs.fp_q[reg - UNW_AARCH64_V0];
   else
```

**Pull request merged**
