### PR TITLE
Bump to release 1.7.1

### LINKED ISSUE #535: 1.7.0 package name and version in pkg-config files are broken
First, thanks for the release, but the 1.7.0 package name is broken, it reads `libunwind-1.70.tar.gz`.

The reason is the missing `.` between `pkg_minor` and `pkg_suffix` in `mkvers`. This was changed in the 1.6 release branch 9a0de16192977b609691e824c900b628d623510b.

### PR DESCRIPTION
**Pull request by bregma**
Fixes format of release number string for proper semantic versioning.

Closes #535

### CODE REVIEW

**Comment by lemul** [comment]
+1, it would be nice to new release due to many fixes atleast for FreeBSD. 10x

**Comment by lemul** [comment]
> > it would be nice to new release due to many fixes atleast for FreeBSD.
> 
> I'm aiming for a 1.8 release in the August timeframe to pick up the QNX and FreeBSD changes. It's not quite the yearly cadence of previous releases but there's been more activity lately.
> 
That's a great plan for me,
from the FreeBSD perspective all required changes are commited into the main branch

> The big thing that's still outstanding is getting the (Linux) CI green(er).
You mean those weird errors with -O3 -O0 on x86?

**Comment by bregma** [comment]
> You mean those weird errors with -O3 -O0 on x86?

Exactly. #569 seems to be a problem with signal trampoline detection that only shows up in optimized code, which kind of smells like undefined behaviour somewhere, but nothing shows up with ubsan. It's a little disconcerting.

PPC, MIPS, and 32-bit ARM may just need to be demoted to second-line support targets since they've been broken for a long time unless someone steps up.

**Comment by lemul** [comment]
> > You mean those weird errors with -O3 -O0 on x86?
> 
> Exactly. #569 seems to be a problem with signal trampoline detection that only shows up in optimized code, which kind of smells like undefined behaviour somewhere, but nothing shows up with ubsan. It's a little disconcerting.
> 

-1 from unw_step() is a UNW_UNSPEC? However, I dont see where on x86 Linux UNW_UNSPEC is returned, so it seems that -1 is result from some libc call.

> PPC, MIPS, and 32-bit ARM may just need to be demoted to second-line support targets since they've been broken for a long time unless someone steps up.

**Pull request merged**
