### PR TITLE
arm: FreeBSD/ARMv6 port

### PR DESCRIPTION
**Pull request by djwatson**
arm/aarch64 patch backlog needing testing

### CODE REVIEW

**Comment by djwatson** [comment]
@kostikbel Finally getting to merging this patch - can you verify the rebase was correct?  There were a few conflicts from other arm patches.  Thanks

**Comment by kostikbel** [comment]
The visual inspection of the merge looks fine.  If there is no regressions on other platforms caused by the change, please commit it as is.

I do not have my RPI2 working ATM, so I cannot check immediately.  I will either revive the machine myself or find somebody to test.

**Comment by djwatson** [comment]
Thanks, will do.

**Comment by djwatson** [comment]
merged.

**Pull request closed without merging**
