### PR TITLE
Expose register states

### PR DESCRIPTION
**Pull request by unkadoug**
Let others use libunwind to process dwarf data for a procedure, save the register update states for popping the stack from every point in the procedure, and that use those saved updates laster, to complete a unw_step up the stack without recomputing the update data.

### CODE REVIEW

**Comment by djwatson** [comment]
Success!  It looks clean now, thanks.

**Comment by unkadoug** [comment]
I'm going to have to make another change, to save and restore the ret_addr_column as part of the register state.

**Comment by unkadoug** [comment]
After the most recent change, I believe that dwarf.ret_addr_column is a write-only variable, and can be removed.

**Comment by unkadoug** [comment]
If review is suspended awaiting some further action from me, please let me know.

**Comment by djwatson** [comment]
Series looks good to me, thanks. 

Can you add a test to cover the new user-facing functionality?

**Comment by unkadoug** [comment]
I'm passing this test, and the travis builder fails without providing information.  Give me a hint, please.

**Comment by djwatson** [comment]
I added some printf statements:

pre consume
Consumed
rlimit 0
rlimit 0
prebacktrace
0000000000400bc9 (sp=00007fff6e2870b0)
IP not in range?
IP not in range?
IP not in range?
memcpy
IP not in range?
IP not in range?
IP not in range?
IP not in range?
after iterate
after apply
0000000000400aa7 (sp=00007fff6e289fb0)
IP not in range?
IP not in range?
IP not in range?
IP not in range?
IP not in range?
memcpy
after iterate
after apply
00007fab58caa7ed (sp=00007fff6e289fd0)
IP not in range?
IP not in range?
IP not in range?
IP not in range?
IP not in range?
IP not in range?
memcpy
after iterate
after apply
0000000000400ae5 (sp=00007fff6e28a090)
after iterate
/home/travis/.travis/job_stages: line 54: 18526 Segmentation fault      (core dumped) ./tests/test-reg-state

https://github.com/djwatson/libunwind/commit/84b64c563c9673816d9c63b49b2d6c26999e2285

It looks like one of the unw_reg_states_iterate() calls is never calling the callback function, and the test then tries to apply an empty reg state.

**Comment by unkadoug** [comment]
Thanks for the assist.

**Comment by unkadoug** [comment]
When might this pull request be merged into master?

**Comment by djwatson** [comment]
I squashed the test commits, but otherwise merged as-is. 

Thanks Doug

**Comment by unkadoug** [comment]
Thanks very much for the quick response.

**Pull request closed without merging**
