### PR TITLE
Don't force {exec_prefix}/lib64 libdir on ppc64

### PR DESCRIPTION
**Pull request by matthiasdiener**
See also https://sources.debian.org/patches/libunwind/1.3.2-2/20140507-ppc_lib64.patch/

### CODE REVIEW

**Comment by kasperk81** [comment]
:+1: most (if not all) the Debian and Gentoo patches have been upstreamed in one form or the other. Would be nice to cut the v1.6 soon with RISC-V support (#267), so we can get a robust/patch-free libunwind available in packages.

**Comment by matthiasdiener** [comment]
The CI failure seems to be spurious

**Comment by kasperk81** [comment]
Yes, that intermittent test hang in s390x CI leg is something which @uweigand might be able to help with. :eyes:

**Comment by uweigand** [comment]
> Yes, that intermittent test hang in s390x CI leg is something which @uweigand might be able to help with. eyes

I notice that the single test that is not reported as PASS in the travis log is test-async-sig.   However, I'm not able to reproduce any hang on my machine (Ubuntu 20.04) even after many re-runs.

That said, the test-async-sig test seems to test the system (e.g. proper unwind info everywhere in glibc) just as much as the actual libunwind code base, so this may simply be a problem in the environment.  Do you know which OS is installed on the travis builder?

**Comment by matthiasdiener** [comment]
Closing/reopening to restart CI

**Comment by kasperk81** [comment]
@uweigand, from [logs](https://app.travis-ci.com/github/libunwind/libunwind/jobs/522056699#L7) this build info is shown:

```
Build image provisioning date and time
Mon Jan 20 10:45:28 UTC 2020
Operating System Details
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.6 LTS
Release:	16.04
Codename:	xenial
Linux Version
5.3.0-26-generic
```

**Comment by uweigand** [comment]
@kasperk81 thanks, I did not notice this.   Ubuntu 16.04 is quite old - I believe it is already out of support unless you have a paid-for extended maintenance contract, so even if we did identify a bug there, it's unlikely we would be able to fix it at this stage.

I don't know exactly how this works with Travis - Is there a way to move to a more recent OS version?

**Comment by kasperk81** [comment]
Indeed 16.04 has reached EOL. It is possible to move the builds to GitHub Actions, but GitHub Actions does not support s390x architecture natively. We can run the build in qemu/docker, but testing libunwind would not yield the same result as baremetal.

BTW, yesterday libunwind's TravisCI account ran out of credits, so it's not a free option anymore. Another reason to consider GitHub Actions with some compromises (that we cannot reliable run s390x tests there, and only reliably cross-compile the code on that arch for validation).

**Comment by zhaofengli** [comment]
> We can run the build in qemu/docker, but testing libunwind would not yield the same result as baremetal.

I don't think there is any difference between testing in qemu and on baremetal for this. It's just that setting it up is a bit tricky (we cannot use qemu-user and have to use full-system emulation).

**Comment by kasperk81** [comment]
BTW, run-coredump-unwind and run-coredump-unwind-mdi both tests consistently fail on Ubuntu 18.04 and 20.04 x86_64. It is either the old version of gcc/g++ (some tests are in C++) or something else in that environment libc/kernel that makes them succeed on 16.04 (which has already reached its end of life and CI vendors are moving on from it). We should disable that test or fix the reason why https://github.com/libunwind/libunwind/blob/c720133faa27293a0e8e075ddf9ccefa55a2efa1/tests/test-coredump-unwind.c#L377-L380 condition satisfies (test_cur is 1 instead of 4, test_start_ips[1] is 1 and test_start_ips[2] is -1 on ubuntu focal with -O0, -O2 as well as -O3)...

**Pull request merged**
